name: Build and Release Binary

on:
  push:
    tags:
      - 'deno-v*'  # Triggers on version tags like v1.0.0

permissions:
  contents: write # Needed to create releases and upload assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Build all binaries
        run: deno task build-all

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: builds/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
